# Generated by Django 4.0.6 on 2022-07-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_house_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrecord',
            name='confirmatin_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
